whale/web_auth/urls.py
from django.urls import path

from . import views

app_name = "web_auth"
urlpatterns = [
    path('', views.InicioView.as_view(), name="inicio"),
    path('login', views.BasicLoginView.as_view(), name='login'),
    path('registro', views.RegistroView.as_view(), name='registro'),
    path('logout', views.LogoutView.as_view(), name='logout'),
    path('dashboard', views.DashBoardView.as_view(), name='dashboard'),
    path('login/qrauth/<str:payload>', views.OTPLoginView.as_view(), name='otpLogin'),
    path('otp/devices/register', views.OTPManageDeviceView.as_view(), name='otpDeviceAdd'),
    path('otp/devices/<str:otp_device>/logincode', views.OTPLoginCodeView.as_view(), name='otpDeviceLoginCode'),
    path('otp/devices/<str:otp_device>/remove', views.OTPDeleteDeviceView.as_view(), name='otpDeviceRemove'),
    path('otp/devices/<str:otp_device>/sync', views.OTPDeviceSecretView.as_view(), name='otpDeviceSyncCode')
]

whale/whale/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('web_auth.urls')),
    path('admin/', admin.site.urls),
]

whale/web_auth/models.py
import pyotp
from django.conf import settings
from django.db import models


class OTPDevice(models.Model):
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
    )
    otp_key = models.CharField(max_length=16)
    name = models.CharField(max_length=100)

    def is_valid_code(self, challenge):
        totp = pyotp.TOTP(self.otp_key)
        return totp.verify(challenge)

    def get_sync_code(self,email, issuer=''):
        otp_secret = self.otp_key
        return pyotp.TOTP(otp_secret).provisioning_uri(email, issuer_name=issuer)

    def gen_otp_code(self):
        return pyotp.TOTP(self.otp_key).now()

    def __str__(self):
        return f"{self.user}: {self.name}"

    @classmethod
    def create(cls, user, name):
        otp_device = cls(
            user_id=user,
            otp_key=pyotp.random_base32(),
            name=name
        )
        return otp_device

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=['user', 'name'],
                name='otp_device_name_unique'
            )
        ]

whale/web_auth/forms.py
from django import forms

CAMPOS_LOGIN_MAPEO = {
    'password': 'pass'
}


class BasicLoginForm(forms.Form):
    usuario = forms.CharField()
    password = forms.CharField()

    def add_prefix(self, field_name):
        field_name = CAMPOS_LOGIN_MAPEO.get(field_name, field_name)
        return super(BasicLoginForm, self).add_prefix(field_name)


class RegistroForm(forms.Form):
    usuario = forms.CharField()
    correo = forms.EmailField()
    nombre = forms.CharField()
    password = forms.CharField()

    def add_prefix(self, field_name):
        field_name = CAMPOS_LOGIN_MAPEO.get(field_name, field_name)
        return super(RegistroForm, self).add_prefix(field_name)


class AgregarOTPDeviceForm(forms.Form):
    otp_name = forms.CharField()

whale/web_auth/views.py
import io

from PIL import Image
from django.http import HttpResponseServerError, HttpResponse
from django.shortcuts import render, redirect
from django.views.generic.base import TemplateView
from django.views import View
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.urls import reverse
from .forms import BasicLoginForm, RegistroForm, AgregarOTPDeviceForm
from .models import OTPDevice
import qrcode
import base64


def gen_qr_code(string):
    qr_gen = qrcode.QRCode(
        version=1,
        error_correction=qrcode.constants.ERROR_CORRECT_L,
        box_size=10,
        border=4)
    qr_gen.add_data(string)
    qr_gen.make(fit=True)
    qr_img = qr_gen.make_image()
    img = io.BytesIO()
    qr_img.save(img, format="PNG")
    img.seek(0)
    return img


class InicioView(TemplateView):
    template_name = "web_auth/inicio.html"


class DashBoardView(LoginRequiredMixin, TemplateView):
    template_name = "web_auth/dashboard.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['otp_devices'] = OTPDevice.objects.filter(user=self.request.user.id)
        return context


class BasicLoginView(TemplateView):
    template_name = "web_auth/login.html"

    def post(self, request):
        form = BasicLoginForm(request.POST)
        if form.is_valid():
            usuario = form.cleaned_data.get("usuario")
            password = form.cleaned_data.get("password")
            credentials = authenticate(request, username=usuario, password=password)
            if credentials:
                login(request, credentials)
                return redirect(reverse('web_auth:dashboard'))
        return redirect(reverse('web_auth:login'))


class OTPLoginView(View):
    def get(self, request, payload):
        payload = base64.decodebytes(payload.encode('utf-8')).decode('utf-8').split(':')
        try:
            credentials = authenticate(request, username=payload[0], challenge=payload[1])
            if credentials:
                login(request, credentials)
                return redirect(reverse('web_auth:dashboard'))
            return redirect(reverse('web_auth:login'))
        except KeyError:
            HttpResponseServerError("Información Malformada")


class OTPManageDeviceView(LoginRequiredMixin, View):
    def post(self, request):
        form = AgregarOTPDeviceForm(request.POST)
        if form.is_valid():
            otp_name = form.cleaned_data.get("otp_name")
            if not OTPDevice.objects.filter(name=otp_name).exists():
                otp_device = OTPDevice.create(user=self.request.user.id, name=otp_name)
                otp_device.save()
        return redirect('web_auth:dashboard')


class OTPDeleteDeviceView(LoginRequiredMixin, View):
    def post(self, request, otp_device):
        otp_device = OTPDevice.objects.get(user=self.request.user.id, name=otp_device)
        if otp_device is not None:
            otp_device.delete()
            return redirect('web_auth:dashboard')


class OTPDeviceSecretView(LoginRequiredMixin, View):
    def get(self, request, otp_device):
        otp_device = OTPDevice.objects.get(user=self.request.user.id, name=otp_device)
        if otp_device is not None:
            otp_secret = otp_device.get_sync_code(self.request.user.email, request.META['HTTP_HOST'])
            img = gen_qr_code(otp_secret)
            return HttpResponse(img.read(), content_type="image/png")
        error_img = Image.new('RGBA', (1, 1), (0, 0, 0, 255))
        response = HttpResponse(content_type="image/png")
        error_img.save(response, "PNG")
        return response


class OTPLoginCodeView(LoginRequiredMixin, View):
    def get(self, request, otp_device):
        otp_device = OTPDevice.objects.get(user=self.request.user.id, name=otp_device)
        if otp_device is not None:
            otp_code = otp_device.gen_otp_code()
            payload = base64.urlsafe_b64encode(f"{self.request.user.username}:{otp_code}"
                                               .encode('utf-8')).decode('utf-8')
            ruta = f"http{'s' if request.is_secure() else ''}://{request.META['HTTP_HOST']}/login/qrauth/"
            ruta += payload
            img = gen_qr_code(ruta)
            return HttpResponse(img.read(), content_type="image/png")
        error_img = Image.new('RGBA', (1, 1), (0, 0, 0, 255))
        response = HttpResponse(content_type="image/png")
        error_img.save(response, "PNG")
        return response


class RegistroView(View):
    def registrar(self, usuario, correo, nombre, password):
        if not User.objects.filter(username=usuario).exists():
            usuario = User.objects.create_user(usuario, correo, password)
            usuario.first_name = nombre
            usuario.save()
            return True
        return False

    def post(self, request):
        form = RegistroForm(request.POST)
        if form.is_valid():
            usuario = form.cleaned_data.get("usuario")
            correo = form.cleaned_data.get("correo")
            nombre = form.cleaned_data.get("nombre")
            password = form.cleaned_data.get("password")
            if self.registrar(usuario, correo, nombre, password):
                return redirect('web_auth:login')
        return redirect('web_auth:login')


class LogoutView(View):
    def get(self, request):
        logout(request)
        return redirect(reverse('web_auth:inicio'))

whale/web_auth/templates/web_auth/dashboard.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
{% load static %}

<head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="{% static 'web_auth/css/style-dashboard.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"/>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css2?family=Raleway:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <title>
        {% if nombre %}
        {{ nombre }}
        {% endif %}
    </title>
    <script src="{% static 'web_auth/js/otp_upd.js' %}"></script>
    <style>
        .foto_perfil {
            max-width: 100px;
        }
        .qr{
            max-width: 250px;
        }
    </style>
</head>

<body>


    <nav class="navbar  sticky-top navbar-custom flex-md-nowrap shadow">
                <button class="navbar-toggler position-absolute d-md-none collapsed" type="button" data-toggle="collapse" data-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
            
            
            <input class="form-control form-control-dark" type="text" placeholder="Search" aria-label="Search">

            <div class="NombrePerfil">
            <img class="foto-perfil" src="{% static 'web_auth/images/profile-default.png' %}" alt="profile pic">
            <a class="navbar-brand col-md-3 col-lg-2 mr-0 px-3" href="#">{{ user.get_username }}</a>
            </div>
    
            <div class="nav-item text-nowrap">
            <button onclick="location.href='/logout'">Cerrar Sesion</button>
            </div>

             <div class="dropdown">
  <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    Dropdown button
  </button>
  <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
    <a class="dropdown-item" href="#">Action</a>
    <a class="dropdown-item" href="#">Another action</a>
    <a class="dropdown-item" href="#">Something else here</a>
  </div>
</div>
    </nav>



<div class="container-fluid">
  <div class="row">
  <div class="col-sm-3">
  <div class="sidebar">
  <a class="active" href="#home">Dashboard</a>
  <a href="#news">News</a>
  <a href="#contact">Contact</a>
  <a href="#about">About</a>
</div>
</div>

    <div class="col-sm-6">
      <div class="content">

            <div class="animate__animated animate__fadeInUp animate__slow">
            <h2> Inicio</h2>
            </div>
            
           
           

            
            
       
        <form id="form-login" action="{% url 'web_auth:otpDeviceAdd' %}" method="POST">
        <div class="Dispositivo">
            <h2>Agregar un nuevo dispositivo</h2>
            {% csrf_token %}
            <label>
                Nombre del Dispositivo:
                <input type="text" id="otp_name" name="otp_name">
                <button type="submit">Agregar nuevo dispositivo</button>
            </label>
        </div>
        </form>
        <hr>

   

        

        {% if otp_devices.count == 0 %}
        <h3>No hay dispositos actualmente</h3>
        {% else %}
        <table id="otp_devices">
            <thead>
                <tr>
                    <th>Nombre</th>
                    <th>Codigo Sync</th>
                    <th>Codigo Actual</th>
                    <th>Eliminar</th>
                </tr>
            </thead>
            <tbody>


                {% for otp_device in otp_devices %}
                <tr>
                    <td>{{ otp_device.name }}</td>

                    <td><img class="qr" src="{% url 'web_auth:otpDeviceSyncCode' otp_device=otp_device.name %}" alt="codigo sync"></td>
                    <td>
                        <img class="qr" src="{% url 'web_auth:otpDeviceLoginCode' otp_device=otp_device.name %}" alt="codigo login">
                    </td>
                    <td>
                        <form action="{% url 'web_auth:otpDeviceRemove' otp_device=otp_device.name %}" method="POST">
                            {% csrf_token %}
                            <button type="submit">Eliminar</button>
                        </form>
                    </td>

                </tr>
                {% endfor %}


            </tbody>
        </table>
        {% endif %}
          </div>
          
    </div>
    <div class="col-sm-3">
        <div class="Calendario">
            <p>Martes</p>
            <p>Octubre 10, 2020</p>
        </div>
        <div class="month">      
  <ul>
    <li class="prev">&#10094;</li>
    <li class="next">&#10095;</li>
    <li>
      Octubre<br>
      <span style="font-size:18px">2020</span>
    </li>
  </ul>
</div>

<ul class="weekdays">
  <li>Mo</li>
  <li>Tu</li>
  <li>We</li>
  <li>Th</li>
  <li>Fr</li>
  <li>Sa</li>
  <li>Su</li>
</ul>

<ul class="days">  
  <li>1</li>
  <li>2</li>
  <li>3</li>
  <li>4</li>
  <li>5</li>
  <li>6</li>
  <li>7</li>
  <li>8</li>
  <li>9</li>
  <li><span class="active">10</span></li>
  <li>11</li>
  <li>12</li>
  <li>13</li>
  <li>14</li>
  <li>15</li>
  <li>16</li>
  <li>17</li>
  <li>18</li>
  <li>19</li>
  <li>20</li>
  <li>21</li>
  <li>22</li>
  <li>23</li>
  <li>24</li>
  <li>25</li>
  <li>26</li>
  <li>27</li>
  <li>28</li>
  <li>29</li>
  <li>30</li>
  <li>31</li>
</ul>
    </div>
  </div>
</div>
        
   
    <script>
        function refresh(node, tiempo) {
            (function startRefresh() {
                let address;
                if (node.src.indexOf('?') > -1)
                    address = node.src.split('?')[0];
                else
                    address = node.src;
                node.src = address + "?time=" + new Date().getTime();

                setTimeout(startRefresh, tiempo);
            })();

        }

        window.onload = function () {
            let table = document.getElementById("otp_devices");
            if (table != null) {
                for (let i = 1, row; i < table.rows.length; i++) {
                    row = table.rows[i];
                    let node = row.cells[2];
                    refresh(node.getElementsByTagName("img")[0], 15 * 1000);
                }
            }
        }


    </script>
    


<div class="footer">
   <p class="Descripcion">
        Para usar el Codigo Sync se recomienda utilizar <strong> Google Authenticator</strong> para
            <label>
                <a href="https://play.google.com/store/apps/details?id=com.google.android.apps.authenticator2&hl=es"  target="_blank" >Android </a>
            </label>

            <label>
                <a href="https://apps.apple.com/es/app/google-web_authenticator/id388497605" target="_blank" >IOS</a>
            </label>
    </p>

   

</div>





</body>

</html>

whale/web_auth/templates/web_auth/inicio.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
{% load static %}

<head>
    <meta charset="utf-8">
    <title></title>

   
    <link rel="stylesheet" href="{% static 'web_auth/css/style-inicio.css' %}">
    <link href="https://fonts.googleapis.com/css2?family=Raleway:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"/>
    <link href="https://fonts.googleapis.com/css2?family=Raleway:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">
    <script src="{% static 'web_auth/js/typewriter.js' %}"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1">
</head>

<body>

    <div class="container">
            <div id="cloud-intro"></div>
    </div>

    <div class="animate__animated animate__bounceInDown">
            <div class="Titulo">
                <a href="{% url 'web_auth:login' %}">Bienvenidos a la nueva Aula Virtual</a>
            </div>
                    <h2 href="" class="typewrite" data-period="2000" data-type='[ "Nuevo Diseño.", "Creativo.", "Interesante.", "Innovador" ]'>
                         <span class="wrap"></span>
                    </h2>
    </div>


</body>

</html>

whale/web_auth/templates/web_auth/login.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
{% load static %}

<head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="{% static 'web_auth/css/dark-style.css' %}">
    <link rel="stylesheet" href="{% static 'web_auth/css/style.css' %}">
    <link href="https://fonts.googleapis.com/css2?family=Raleway:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"/>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

    <!--https://github.com/mebjas/html5-qrcode-->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script src="{% static 'web_auth/js/lib/html-qrcode.js' %}"></script>

</head>

<body>

    <style>
        #lectorQR {
            max-width: 800px;
            max-height: 600px;
        }
    </style>


    <div class="animate__animated animate__fadeIn">
    <div class="imagen-form">
    <div class="login-form formulario">

        <div>
             <img class="Logo-UNA" src="/static/web_auth/images/UNALOGO.png">
                <h6 class="animate__animated animate__fadeInRight">Iniciar Sesion</h6>
        </div>

        <div id="lectorQR" width="800px" height="600px"></div>
       
            <form id="form-login" action="{% url 'web_auth:login' %}" method="POST">
                {% csrf_token %}

                <div class="animate__animated animate__fadeInUp animate__slow">
                    <div class="campo-entrada">
                        <input type="text" id="usuario" name="usuario" placeholder=" " {% if correo %} value="{{ correo }}"
                                {% endif %} required>
                <label for="usuario"> <i class="fa fa-user icon"></i>Usuario</label>
                    </div>

                    <div class="campo-entrada">
                        <input type="password" id="pass" name="pass" placeholder=" " {% if password %} value="{{ password }}"
                                {% endif %} required>          
                <label for="pass"><i class="fa fa-key icon"></i>Contraseña</label>
                   </div>
                </div>

            <button class="submit" id="login">Iniciar Sesion</button>
            <button class="submit" id="registrar" formaction="{% url 'web_auth:registro' %}">Registrarse</button>  

            </form>


        <form>
            
            <button class="submit" formaction="/google-login">
                Iniciar sesion con google
            </button>
            
            <button class="submit" type="button" onclick=";iniciarCaptura()">
                Escanear codigo QR
            
            </button>
        </form>

    </div>
    </div>
    </div>


    <script>
        let nombre = document.getElementById("nombre");
        let correo = document.getElementById("correo")
        document.getElementById("registrar").addEventListener("click", function (event) {
            if (!nombre) {
                document.getElementById("login").style.display = 'none';
                nombre = document.createElement("div");
                let campo = document.createElement("input");
                let etiqueta = document.createElement("label");
                nombre.className = "campo-entrada";
                campo.type = "text";
                campo.id = "nombre";
                campo.placeholder = " ";
                campo.name = "nombre";
                {% if nombre %}
                campo.value = "{{nombre}}"
                {% endif %}
                campo.required = true;
                etiqueta.htmlfor = campo;
                etiqueta.innerText = "Nombre Completo";
                nombre.appendChild(campo);
                nombre.appendChild(etiqueta);
                document.getElementById("form-login").prepend(nombre);
                event.preventDefault()
            }
            if (!correo) {
                correo = document.createElement("div");
                let campo = document.createElement("input");
                let etiqueta = document.createElement("label");
                correo.className = "campo-entrada";
                campo.type = "email";
                campo.id = "correo";
                campo.placeholder = " ";
                campo.name = "correo";
                {% if correo %}
                campo.value = "{{correo}}"
                {% endif %}
                campo.required = true;
                etiqueta.htmlfor = campo;
                etiqueta.innerText = "Correo Electronico";
                correo.appendChild(campo);
                correo.appendChild(etiqueta);
                document.getElementById("form-login").prepend(correo);
                event.preventDefault()
            }


        });
    </script>
    
    <script>
        function filtrarCodigo(texto) {
            return texto.match("([^\/]+(^(?=(.{4})*$)[A-Za-z0-9\-_]*)*(==)$)")
        }
        function iniciarCaptura() {
            Html5Qrcode.getCameras().then(devices => {

                if (devices && devices.length) {
                    let longitud = document.getElementById("lectorQR").getBoundingClientRect().width
                    let config = { qrbox: 250 };
                    if (longitud > 100 && longitud < config.qrbox) {
                        config.qrbox = longitud * .8;
                    }
                    else if (longitud < config.qrbox) {
                        config = {};
                    }
                    const html5QrCode = new Html5Qrcode("lectorQR");
                    const camara = { facingMode: "environment" }

                    html5QrCode.start(
                        camara,
                        config,
                        qrCodeMessage => {
                            let texto = filtrarCodigo(qrCodeMessage)
                            if (texto) {
                                html5QrCode.stop().then(ignore => {
                                    location.href = "{% url 'web_auth:otpLogin' payload='-' %}".slice(0, -1) + texto;
                                }).catch(err => {
                                    alert("no se ha podido detener la grabacion de la camara")
                                });
                            }
                        },
                        errorMessage => { }
                    )
                        .catch(err => {
                            alert("ha ocurrido un error al escanear la camara")
                        });
                }
                else {
                    alert("no hay camaras disponibles")
                }
            }).catch(err => {
                alert("no se ha podido obtener permisos de la camara")
            });
        }
    </script>


</body>

</html>